name: gsheet.action Update-data
on:
  schedule: 
  - cron: '0 1 * * *'
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - id: 'download_gsheet_data'
        uses: jroehl/gsheet.action@v1.0.0 
        with:
          spreadsheetId: <spreadsheetId>
          commands: | 
            [
              { "command": "updateData", "args": { "data": [["A1", "A2", "A3"]] }},
              { "command": "getData", "args": { "range": "'<worksheetTitle>'!A2:B3" } }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: dump results
        env:
          #  the output of the action can be found in ${{ steps.update_worksheet.outputs.results }}
          RESULTS: ${{ steps.update_worksheet.outputs.results }}
        run: echo "$RESULTS" | jq
      - id: 'clean_data'
      uses: actions/checkout@v2
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 
      name: run python script 
      run: python my_script.py
